# frozen_string_literal: true

customize_gemfiles do
  {
    single_quotes: true,
    heading: <<~HEADING.strip
      frozen_string_literal: true

      This file was generated by Appraisal
    HEADING
  }
end

appraise 'rubocop-1.81' do
  gem 'rubocop', '~> 1.81'
end
